### ISSUE TITLE
collection iterator

### ISSUE THREAD

**Issue by geospatial-jeff** [developmentseed/geojson-pydantic#11]
What do we think about turning `FeatureCollection` and `GeometryCollection` into iterators?

I think this:
```python
for feat in fc:
    ...
```

is nicer than this:
```python
for feat in fc.features:
    ...
```

**Comment by drewbo** [comment]
@geospatial-jeff seems pretty nice; are there any examples of similar libraries having this sort of API (shapely, pygeos, etc)?

**Comment by geospatial-jeff** [comment]
Yeah all shapely multipart geometries have this feature (https://github.com/Toblerity/Shapely/blob/master/shapely/geometry/base.py#L892-L908)

**Comment by drewbo** [comment]
https://github.com/developmentseed/geojson-pydantic/pull/12 work or need something fancier?
