### ISSUE TITLE
Nested GeometryCollection?

### ISSUE THREAD

**Issue by eseglem** [developmentseed/geojson-pydantic#110]
I know the spec discourages them:
>  To maximize interoperability, implementations SHOULD avoid nested GeometryCollections. Furthermore, GeometryCollections composed of a single part or a number of parts of a single type SHOULD be avoided when that single part or a single object of multipart type (MultiPoint, MultiLineString, or MultiPolygon) could be used instead.

But I ran into an interesting case while working on pycql2. Trying to translate from WKT to GeoJSON gets weird because  `GEOMETRYCOLLECTION(POINT(0 0), GEOMETRYCOLLECTION(POINT(1 1), LINESTRING(0 0, 1 1)))` is technically a valid WKT. And shapely will load it in, as well as output it as nested GeoJSON.

```python
>>> from shapely import wkt, to_geojson
>>> print(to_geojson(wkt.loads("GEOMETRYCOLLECTION(POINT(0 0), GEOMETRYCOLLECTION(POINT(1 1), LINESTRING(0 0, 1 1)))")))
# Manually formatted for readability
{
  "type": "GeometryCollection",
  "geometries": [
    {"type": "Point", "coordinates": [0.0, 0.0]},
    {
      "type": "GeometryCollection",
      "geometries": [
        {"type": "Point", "coordinates": [1.0, 1.0]},
        {"type": "LineString", "coordinates": [[0.0, 0.0], [1.0, 1.0]]}
      ]
    }
  ]
}
```

So, despite the spec saying not to do it for interoperability reasons, I would actually say the ability to parse it is needed for interoperability. 

What if we included it and throw a warning about it? Something like this: 

```python
from __future__ import annotations
import warnings

class GeometryCollection(BaseModel, GeoInterfaceMixin):
    type: Literal["GeometryCollection"]
    geometries: List[Union[Geometry, GeometryCollection]]

    ...

    @validator("geometries")
    def check_geometries(cls, geometries: List) -> List:
        """Add warnings for conditions the spec does not explicitly forbid."""
        if len(geometries) == 1:
            warnings.warn("GeometryCollection should not be used for single geometries.")
        if any(geom.type == "GeometryCollection" for geom in geometries):
            warnings.warn(
                "GeometryCollection should not be used for nested GeometryCollections."
            )
        if len(set(geom.type for geom in geometries)) == 1:
            warnings.warn(
                "GeometryCollection should not be used for homogeneous collections."
            )
```

Could also have it check something in the Class Config and throw validation errors instead of warnings. Maybe a `Config.strict_geometry_collection`. Then would be able to subclass it and set the config and use it however preferred.

**Comment by vincentsarago** [comment]
well SHOULD is not MUST NOT so I guess you're right. 

I think a warning should be enough.
