### ISSUE TITLE
Errors in bbox validation logic?

### ISSUE THREAD

**Issue by bmschmidt** [developmentseed/geojson-pydantic#118]
Thanks for writing and maintaining this useful library, and apologies if my issue/PR betray some fundamental misunderstanding(s).

The 0.6.0 update seems to have broken our CI pipeline. As best I can tell, this relates a collision of expectations related to the new bbox validation on features, and to the need for explicit `None`s: we don't include bboxes for our features, and I think somehow that lack is getting turned into an explicit `None` which then raises an error when the bbox validation takes its `len`.

It also appears to me that the bbox tests were possibly raising ValueErrors for multiple reasons: they were missing geometries and so raised an error even if the bboxes were correct. I've added an assertion to make sure that they succeed.

I'm filing a related PR that I believe fixes these issues.

**Comment by vincentsarago** [comment]
@bmschmidt I'm sorry we broke stuff :-( 

Could you share a sample of code that used to work with 0.5 and is not with 0.6 ?

**Comment by bmschmidt** [comment]
No worries about breaking things, we're so grateful that someone is taking on the work of maintaining these models! And we know we live on the bleeding edge by not pinning versions...

Unfortunately I can't easily mock up a reproducible example--the stack here is that we're using pydantic to validate inputs/outputs over a JSON API running over [fastAPI](https://fastapi.tiangolo.com/tutorial/query-params-str-validations/?h=) Examining some of our endpoints it appears that even under geojson-pydantic 0.5.0 the FeatureCollections we're pushing out explicitly have `null` keys getting set for `id` and `bbox`, which is certainly related to the problem we've been hitting here. I'm not sure if it's pydantic or fastAPI that introduces those into the data--our code doesn't set either.

 Example output from our current production stack, which passes validation. (Although probably it shouldn't? [`null` isn't a valid value for bbox.](https://datatracker.ietf.org/doc/html/rfc7946#:~:text=A%20GeoJSON%20object%20MAY%20have%20a%20%22bbox%22%20member%2C%20the%20value%20of%20which%20MUST%0A%20%20%20%20%20%20be%20a%20bounding%20box%20array))
 
```json
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          15.90476440429688,
          -4.774862899780273
        ]
      },
      "properties": {
        "depth": 1,
        "topic": 1,
        "_topic_depth_1": "Health care",
        "topic_description": "health/patients/treatment/disease/cancer/medical/Health/care/cells/skin/blood/pain/symptoms/body/study",
        "topic_short_description": "Health care"
      },
      "id": null,
      "bbox": null
    }]
  }
```
