### ISSUE TITLE
 AttributeError: 'Geometry' is not defined for GeometryCollection model

### ISSUE THREAD

**Issue by arthurdjn** [developmentseed/geojson-pydantic#135]
### Issue

There is an AttributeError being raised if a schema is being generated from the `GeometryCollection`.

```python
from geojson_pydantic.geometries import GeometryCollection

GeometryCollection.model_json_schema()
# AttributeError
```

Here is the traceback:

```
Traceback (most recent call last):
  File ".venv/lib/python3.10/site-packages/pydantic/type_adapter.py", line 149, in __init__
    core_schema = _getattr_no_parents(type, '__pydantic_core_schema__')
  File ".venv/lib/python3.10/site-packages/pydantic/type_adapter.py", line 94, in _getattr_no_parents
    raise AttributeError(attribute)
AttributeError: __pydantic_core_schema__

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".venv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 461, in _generate_schema
    obj = _typing_extra.evaluate_fwd_ref(obj, globalns=self.types_namespace)
  File ".venv/lib/python3.10/site-packages/pydantic/_internal/_typing_extra.py", line 421, in evaluate_fwd_ref
    return ref._evaluate(globalns=globalns, localns=localns, recursive_guard=frozenset())
  File "/usr/lib/python3.10/typing.py", line 694, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Geometry' is not defined
```

### Suggested Change

Looking at the code in the `geometries.py`, it looks like the error is raised because the `Geometry` type alias is defined **after** the `GeometryCollection` model. Switching the two works. Here is a possible fix:

```python
Geometry = Annotated[
    Union[
        Point,
        MultiPoint,
        LineString,
        MultiLineString,
        Polygon,
        MultiPolygon,
        "GeometryCollection",  # Type alias as a string because GeometryCollection is not defined yet
    ],
    Field(discriminator="type"),
]

class GeometryCollection(BaseModel, GeoInterfaceMixin):
    """GeometryCollection Model"""
    # ...
```

### Additional Notes

Why are nested GeometryCollection allowed ? [Looking at the code](https://github.com/developmentseed/geojson-pydantic/blob/d78b841755e5fcbac66adbc069609e1413dd9278/geojson_pydantic/geometries.py#L298) it looks like it is not recommended, then why allowing it in the first place? 

### Versions

*Note that with geojson_pydantic v0.6.3 and pydantic v1.9.1 the above code runs.*

- *geojson_pydantic* latest version from the git
- *pydantic* version 2.0.2

I can work on the PR if you want.

_Originally posted by @arthurdjn in https://github.com/developmentseed/geojson-pydantic/issues/132#issuecomment-1631242566_

**Comment by vincentsarago** [comment]
🙏 thanks for the issue.

Quick note about 👇 

> Why are nested GeometryCollection allowed ? [Looking at the code](https://github.com/developmentseed/geojson-pydantic/blob/d78b841755e5fcbac66adbc069609e1413dd9278/geojson_pydantic/geometries.py#L298) it looks like it is not recommended, then why allowing it in the first place?

Because it's part of the specification, it's allowed but SHOULD be avoided 

>  To maximize interoperability, implementations SHOULD avoid nested
   GeometryCollections.  Furthermore, GeometryCollections composed of a
   single part or a number of parts of a single type SHOULD be avoided
   when that single part or a single object of multipart type
   (MultiPoint, MultiLineString, or MultiPolygon) could be used instead.
