### ISSUE TITLE
Pydantic 2.4 raises "Recursion error - cyclic reference detected"

### ISSUE THREAD

**Issue by PaulVanSchayck** [developmentseed/geojson-pydantic#146]
With Pydantic 2.4, we get the following error when importing Geometry

```
pydantic_core._pydantic_core.SchemaError: Invalid Schema:
definitions.definitions.6.model.schema.model-fields.fields.geometries.schema.function-after.schema.list.items_schema.tagged-union.choices.GeometryCollection
  Recursion error - cyclic reference detected [type=recursion_loop, input_value={'type': 'model', 'cls': ...lection:94472407183040'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.4/v/recursion_loop
```

I suspect this is because `GeometryCollection` is used in `Geometry`. See [here](https://github.com/developmentseed/geojson-pydantic/blob/main/geojson_pydantic/geometries.py#L312).

**Comment by vincentsarago** [comment]
should be fine with pydantic 2.4.2 
thanks for the report 🙏

**Comment by ibuseyo** [comment]
Hello,
I am just trying the basic install in an ec2 machine redhat. Following the most basic setup, when I try to start the server with uvicorn titiler.application.main:app  I get a maybe related Pydantic error 

```
 File "/home/ec2-user/temp/.venv_tiler/lib64/python3.7/site-packages/pydantic/fields.py", line 763, in Field
    raise PydanticUserError('`const` is removed, use `Literal` instead', code='removed-kwargs')
pydantic.errors.PydanticUserError: `const` is removed, use `Literal` instead
```

Testing on a local machine works well. But not going to ec2 is failing. Thanks for any help you can provide

**Comment by vincentsarago** [comment]
@ibuseyo can you try with python 3.8 🙏

**Comment by ibuseyo** [comment]
Thanks! that works!
