### ISSUE TITLE
Feature.model_dump include/exclude not working

### ISSUE THREAD

**Issue by thomas-maschler** [developmentseed/geojson-pydantic#147]
The `include` and `exclude` arguments for the `Feature.model_dump` method have no effect:

Example:
```python

from geojson_pydantic.features import Feature

f = Feature(type="Feature", geometry= {
        "coordinates": [[
           [
             -123.07498674,
             44.04971882
           ],
           [
             -123.07554223,
             44.06248623
           ],
           [
             -123.0625126,
             44.06278031
           ],
           [
             -123.06195992,
             44.05001283
           ],
           [
             -123.07498674,
             44.04971882
           ]]],
        "type": "Polygon"
        }, 
        properties={"a": 1, "b": 2, "c":3})
included = f.model_dump(include={"geometry"})
excluded = f.model_dump(exclude={"geometry"})

expected_keys = ["geometry"]
assert len(included) == len(expected_keys)
for key in expected_keys:
    assert key in included

expected_keys = ["bbox", "type", "properties", "id"]
assert len(excluded) == len(expected_keys)
for key in expected_keys:
    assert key in excluded
```
Expected Behavior:
included should be a dictionary with only one key "geometry"
excluded should be a dictionary with four keys (bbox, type, properties, id)

Actual behavior:
Both results are a dictionary with five keys  (bbox, geometry, type, properties, id)

**Comment by vincentsarago** [comment]
This is due to https://github.com/developmentseed/geojson-pydantic/blob/main/geojson_pydantic/base.py#L55-L68

I'm not sure there is a fix, because with this library we are focusing on following the specification which is why we overwrite the `model_dump` to make sure to create valid geojson. Maybe @eseglem can tell more about this

**Comment by thomas-maschler** [comment]
For reference. I currently work on a PR for bumping up stac-pydantic to Pydantic 2. 
This issue causes the field extensions to fail.

**Comment by vincentsarago** [comment]
@thomas-maschler not sure why and if this is the right approach but you can maybe do something like 

```python
class STACFeature(Feature):
    
    @model_serializer(mode="wrap")
    def _serialize(self, handler):
        data = handler(self)
        for field in self.__geojson_exclude_if_none__:
            if field in data and data[field] is None:
                del data[field]
        return data

```

**Comment by thomas-maschler** [comment]
This works, thanks!

**Comment by eseglem** [comment]
Hmm, that definitely seems odd. The serialization logic should only affect json mode and not a plain `model_dump`. And even that should just be removing extra keys.

I'll try and see if I can figure out what's up with it. I thought I had checked include / exclude working but obviously didn't actually write tests for it. Might be a couple days before I can really dig into it though.

**Comment by eseglem** [comment]
I still need to dig more, but this feels like a pydantic bug. 

If we remove the `@model_serializer` it behaves as expected. When it exists though, it makes `model_dump` not work properly. But it is supposed to be only `when_used="json"` and *should* only affect that, at least in my understanding. 

The even crazier part of it is that `model_dump(mode="json", include={"geometry"})` behaves exactly as expected. 

I put up a PR for a workaround / patch for it though. Just always apply the custom one and check what mode it is.

**Comment by vincentsarago** [comment]
@eseglem I think I've seen something in pydantic issues about a similar problem. I'll have another look.

**Comment by vincentsarago** [comment]
similar issue in pydantic https://github.com/pydantic/pydantic/issues/6575
