### ISSUE TITLE
lat lon validation feasible?

### ISSUE THREAD

**Issue by TheGreatRefrigerator** [developmentseed/geojson-pydantic#16]
Hi all, great work on the models so far 🎉 

I'm wondering if it would make sense to include validation for latitude & longitude for coordinates and bbox?

So to check if coordinate input is in the correct order (lon, lat as per geojson spec) for lat input >90 or <-90

Boundaries checks would be:
-180.0 <= lon <=180.0
-90.0 <=lat <= 90.0

Not sure how to do this.. Is it even possible to validate tuples that don't have a key?

**Comment by geospatial-jeff** [comment]
The [newest version of the geojson spec](https://tools.ietf.org/html/rfc7946#section-4) uses WGS84:

> The coordinate reference system for all GeoJSON coordinates is a geographic coordinate reference system, using the World Geodetic System 1984 (WGS 84) [WGS84] datum, with longitude and latitude units of decimal degrees.

Older versions of the spec allowed other coordinate systems:

> Note: the use of alternative coordinate reference systems was specified in [GJ2008], but it has been removed from this version of the specification because the use of different coordinate reference systems -- especially in the manner specified in [GJ2008] -- has proven to have interoperability issues.

But the spec notes that if interoperability is not an issue, than alternative coordinate systems can be used:

> However, where all involved parties have a prior arrangement, alternative coordinate reference systems can be used without risk of data being misinterpreted.

My concern is that adding coordinate validation specific to a single coordinate system will be too restrictive, as the spec seems to indicate that it is possible to have a geojson object that is not WGS84.  In such a case we might raise validation errors on a "valid" object.  I'm interested in other people's opinions on how the models should be supporting specific coordinate systems if at all.

**Comment by TheGreatRefrigerator** [comment]
Hmm valid point, although i guess in most cases WGS84 will be used.
Maybe an option would be to validate WGS84 by default but make it possible to adjust it to other CRS.

Still not sure if it is even possible to implement the validation, as the Coordinates are not a `BaseModel` but a Tuple..

Anyway, for my use case i can still create Model inheriting from `Polygon` and do the validation there i guess

**Comment by geospatial-jeff** [comment]
> Anyway, for my use case i can still create Model inheriting from `Polygon` and do the validation there i guess

I think this is the best solution for now.

> Still not sure if it is even possible to implement the validation, as the Coordinates are not a `BaseModel` but a Tuple..

A good approach is overriding the `coordinates` validator to also check each coordinate, for `bbox` you could do the same.  Pydantic also lets you define a [custom root type](https://pydantic-docs.helpmanual.io/usage/models/#custom-root-types) which lets you validate each `Coordinate`:

```python
from geojson_pydantic.geometries import Coordinate, Point as _Point
from pydantic import BaseModel, Field, root_validator


class WGS84Coordinate(BaseModel):
    __root__: Coordinate

    @root_validator(pre=True)
    def validate_coords(cls, values):
        if abs(values['__root__'][0]) > 180:
            raise ValueError("invalid longitude")
        if abs(values['__root__'][1]) > 90:
            raise ValueError("invalid latitude")
        return values

    def __iter__(self):
        return iter(self.__root__)

    def __getitem__(self, item):
        return self.__root__[item]


class Point(_Point):
    type: str = Field("Point", const=True)
    coordinates: WGS84Coordinate


pt = Point(coordinates=[-118,34])
assert pt.coordinates[0] == -118
assert pt.coordinates[1] == 34


# This will raise validation error (invalid longitude)
pt = Point(coordinates=[34,-118])

**Comment by TheGreatRefrigerator** [comment]
That's exactly what i need!
You make it look so easy. I was looking at the pydantic root type before, but was a bit deterred by the example as it looked rather complex.
Thank you for the structured example

**Comment by drewbo** [comment]
Thanks @TheGreatRefrigerator @geospatial-jeff; I agree with leaving this out for now because other projections can technically be used. I think the example shown is a good way validate if needed

**Comment by bensdm** [comment]
Hey thanks for this useful library! I have a question related with this kind of validation. Let's say I now want to have a FeatureCollection that validated each geometry according to your defined WGS84Coordinate. Do I need to define again each class ? Can't find a simple way to achieve it, while i thought that was the point of being a generic class.

**Comment by vincentsarago** [comment]
@bensdm sadly it would be a bit verbose 

```python
from typing import List, Union
from pydantic import BaseModel, Field, root_validator

from geojson_pydantic import geometries, features


# Overide the Position Type (with a Pydantic Model)
class Position(BaseModel):
    
    __root__: geometries.Position

    @root_validator(pre=True)
    def validate_coords(cls, values):
        if abs(values['__root__'][0]) > 180:
            raise ValueError("invalid longitude")
        if abs(values['__root__'][1]) > 90:
            raise ValueError("invalid latitude")
        return values

    def __iter__(self):
        return iter(self.__root__)

    def __getitem__(self, item):
        return self.__root__[item]


# Create new Geometries Models
class Point(geometries.Point):
    """Point Model"""

    coordinates: Position

class MultiPoint(geometries.MultiPoint):
    """MultiPoint Model"""

    coordinates: List[Position]


class LineString(geometries.LineString):
    """LineString Model"""

    coordinates: List[Position] = Field(..., min_items=2)


class MultiLineString(geometries.MultiLineString):
    """MultiLineString Model"""

    coordinates: List[List[Position]]


class Polygon(geometries.Polygon):
    """Polygon Model"""

    coordinates: List[List[Position]]


class MultiPolygon(geometries.MultiPolygon):
    """MultiPolygon Model"""

    coordinates: List[List[List[Position]]]

# Geometry Type
Geometry = Union[
    Point,
    MultiPoint,
    LineString,
    MultiLineString,
    Polygon,
    MultiPolygon,
]

# Use Generics and set `features` to have geometries of type `Geometry` (with the constrained coordinates)
FeatureCollection = features.FeatureCollection[
    Geometry,
    features.Props,
]
```
