### ISSUE TITLE
require flit_core in pyproject.toml instead of flit?

### ISSUE THREAD

**Issue by dave-andersen** [developmentseed/geojson-pydantic#164]
Hi - I've been working on getting this working under buildroot, which doesn't install the full 'flit' package by default, and one thing that was blocking was that the pyproject.toml file requires "flit" in build_system instead of "flit_core".

The build works properly if this is changed to be in accordance with the usual pyproject.toml mechanism (see https://packaging.python.org/en/latest/guides/writing-pyproject-toml/ ), though I haven't run tests beyond our use of it.

I'm happy to send a PR but this seemed awfully small for one. :)  but LMK what's easiest for you.

Thanks for providing this, btw - very useful to have these models!

**Comment by vincentsarago** [comment]
happy to review pr for this 🙏

**Comment by dave-andersen** [comment]
Thank you! (Sorry I didn't get a PR to you before you did it yourself, was fighting a lot of fires in our buildroot update unrelated to geojson)
