### ISSUE TITLE
Removing the `geojson` package dependency

### ISSUE THREAD

**Issue by hawkaa** [developmentseed/geojson-pydantic#2]
Hi,

Thank you for a great library!

It does not matter at all, but I was a little confused that `geojson` was included as a dependency when depending on `geojson-pydantic`. Inspecting the source code, it looks like it is used to validate the coordinates.

It shouldn't be too hard turning the validation into pydantic idiomatic validations. AFAIK the functionality that needs to be replicated are in these three methods:

* https://github.com/jazzband/geojson/blob/master/geojson/geometry.py#L82-L89
* https://github.com/jazzband/geojson/blob/master/geojson/geometry.py#L102-L111
* https://github.com/jazzband/geojson/blob/master/geojson/geometry.py#L124-L137

Again, not sure the benefit, but we'll at least get rid of the `geojson` dependency and might improve validation handling by turning it into pydantic validations.

Håkon

**Comment by drewbo** [comment]
@hawkaa yes, this seems like a good idea (I'm always a fan of removing larger dependencies), do you want to start a PR?

**Comment by hawkaa** [comment]
@drewbo Amazing! Yes, I will. Not sure when I'll have the time, but let me have a look at it :)
