### ISSUE TITLE
add model factory?

### ISSUE THREAD

**Issue by vincentsarago** [developmentseed/geojson-pydantic#20]
sometime a user (me) would want to specify the GeoJSON model up to the geometry type (e.g. my geojson is a polygon only)

we can use `pydantic.create_model`: https://pydantic-docs.helpmanual.io/usage/models/#dynamic-model-creation

example: https://github.com/arturo-ai/stac-pydantic/blob/master/stac_pydantic/item.py#L96-L110

**Comment by geospatial-jeff** [comment]
I can see use cases for this feature, are you thinking of this as syntactic sugar for creating a model?

```python
from geojson_pydantic import create_model

poly_model = create_model(type="Polygon")
```

vs.

```python
from geojson_pydantic import Polygon, Feature

class PolyModel(Feature):
    geometry: Polygon

```

**Comment by vincentsarago** [comment]
@geospatial-jeff absolutely!
