### ISSUE TITLE
Version string mismatch

### ISSUE THREAD

**Issue by CF-FHB-X** [developmentseed/geojson-pydantic#24]
When installing `geojson-pydantic==0.2.2` from PyPI, the version numbering is off:

```
>>> import geojson_pydantic
>>> geojson_pydantic.version
'0.2.1'
```

**Comment by vincentsarago** [comment]
thanks for the report @CF-FHB-X 

confirmed : https://github.com/developmentseed/geojson-pydantic/blob/659420caf1f281e7ec09d07d2b1bb2b7f29348a4/geojson_pydantic/__init__.py#L3
