### ISSUE TITLE
add top level exports

### ISSUE THREAD

**Issue by vincentsarago** [developmentseed/geojson-pydantic#25]
```python
# now
from geojson_pydantic.features import Feature, FeatureCollection

# future 
from geojson_pydantic import Feature, FeatureCollection
```
maybe also for geometries

**Comment by kylebarron** [comment]
I'd suggest the core GeoJSON constructs be exposed at the top level. I.e. `Feature`, `FeatureCollection` but also each `Point`, `MultiPoint`, `Polygon`, `MultiPolygon`, `LineString`, `MultiLineString`, and `GeometryCollection` class. But not including any helper functions like `parse_geometry_obj` or the `Geometry` union type (unless that's explicitly defined in the GeoJSON spec).
