### ISSUE TITLE
get rid of `Position` type ?

### ISSUE THREAD

**Issue by vincentsarago** [developmentseed/geojson-pydantic#32]
https://github.com/developmentseed/geojson-pydantic/blob/c1e73935dd9fa67e6b6a740e45e8e8a174e38af9/geojson_pydantic/geometries.py#L24

`Position` is a copy of `Coordinate` and isn't use in geojson-pydantic

cc @drewbo @geospatial-jeff

**Comment by vincentsarago** [comment]
I guess is to export types defined in https://datatracker.ietf.org/doc/html/rfc7946#section-3.1.1, but then we should just use `Position` and not `Coordinate` 🤷‍♂️  ?

**Comment by kylebarron** [comment]
I was just going to mention this while looking at the new PR. 

> I guess it is to export types defined in [datatracker.ietf.org/doc/html/rfc7946#section-3.1.1](https://datatracker.ietf.org/doc/html/rfc7946#section-3.1.1), but then we should just use `Position` and not `Coordinate` 🤷‍♂️ ?

:+1: on this
