### ISSUE TITLE
Create conda-forge recipe

### ISSUE THREAD

**Issue by martinabeleda** [developmentseed/geojson-pydantic#36]
Hey team, 

Firstly thanks for this project. It's exactly what I need (especially the 0.3.0 release).

Just wanted to request permission from you to create a `conda-forge` package for this. I've already created a recipe for this [here](https://github.com/conda-forge/staged-recipes/pull/15038). I'm happy to maintain this moving forward and an option is to also add another maintainer. Please let me know

**Comment by kylebarron** [comment]
I think we have a similar setup to this in `rio-tiler`, where a third party is maintaining the Conda recipe, so I'd expect that's ok, but it would be good for @vincentsarago to chime in.

**Comment by vincentsarago** [comment]
@martinabeleda Please go ahead 🙏

**Comment by drewbo** [comment]
Yes please and thank you for the offer @martinabeleda

**Comment by martinabeleda** [comment]
Good news, this all got finalised yesterday. [Here](https://github.com/conda-forge/geojson-pydantic-feedstock) is the conda-forge feedstock repo and [this](https://anaconda.org/conda-forge/geojson-pydantic) is the package page on conda.

**Comment by vincentsarago** [comment]
thanks @martinabeleda 🙏
