### ISSUE TITLE
Add `from_bbox` class method for Polygon geometry

### ISSUE THREAD

**Issue by vincentsarago** [developmentseed/geojson-pydantic#39]
Creating a Polygon from a bounding box `(xmin, ymin, xmax, ymax)` is something user will do quite often. I think adding a simple class method would make life easier for some people 

```python
Polygon.from_bbox(xmin, ymin, xmax, ymax)
```

https://github.com/developmentseed/geojson-pydantic/blob/c7b5c2c0ea3bea90b918d4a16fae3e6808d41258/geojson_pydantic/geometries.py#L50

**Comment by geospatial-jeff** [comment]
What about 'from_bounds' to align the syntax with other libs like shapely?
