### ISSUE TITLE
`geojson-pydantic` not publishing types

### ISSUE THREAD

**Issue by hawkaa** [developmentseed/geojson-pydantic#5]
When I try to depend on this project and validate my own with `mypy` I get the following error:

```sh
error: Skipping analyzing 'geojson_pydantic.features': found module but no type hints or library stubs
note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports
````

This means type information is not published.

I have made this work on a similar project by adding an empty `py.typed` in the root package directory, like this PR does: https://github.com/hawkaa/pygeojson/pull/11/files

Should I open a PR?

**Comment by hawkaa** [comment]
Excellent! When will a new version be released? @drewbo

**Comment by drewbo** [comment]
`0.2.0` Released 🎉 : https://pypi.org/project/geojson-pydantic/0.2.0/

Thanks for your help on this @hawkaa and let me know if type validation is working correctly

**Comment by hawkaa** [comment]
Thank you!!!

It didn't though. Opened #7 for another try. I'm so sorry!

**Comment by drewbo** [comment]
Added in https://pypi.org/project/geojson-pydantic/0.2.1/
