### ISSUE TITLE
Optional geometry/bbox cannot be set to `None` for `Feature`s

### ISSUE THREAD

**Issue by moradology** [developmentseed/geojson-pydantic#55]
This PR made geometry and bbox optional, but this ends up being a bit of an issue if `None` is explicitly provided. This causes a `ValidationError` (this from stac-pydantic tests):
```
E   pydantic.error_wrappers.ValidationError: 1 validation error for Item
E   geometry
E     none is not an allowed value (type=type_error.none.not_allowed)
```
https://pydantic-docs.helpmanual.io/usage/models/#required-fields

**Comment by vincentsarago** [comment]
closed in #56
