### ISSUE TITLE
Proposal for Geometry class hierarchy reorganization

### ISSUE THREAD

**Issue by philvarner** [developmentseed/geojson-pydantic#58]
There are a few issues I see with the existing class hierarchy:

1. GeometryCollection is defined as a Geometry in GeoJSON, but there's no relationship between it and either _GeometryBase or the Geometry Union.
2. GeometryCollection does not implement __geo_interface__

In some recent code working with these classes, I had to create a special case for GeometryCollection like:

```python
if hasattr(arg, "__geo_interface__"):
    return getattr(arg, "__geo_interface__")
else if (isinstance(arg, GeometryCollection)):
    return arg.dict()
```

I would like to see these reorganized more like the following:

```python
# type is the only attribute here, rather than coordinates
class _GeometryBase(BaseModel, abc.ABC):
    """Base class for Geometry models"""

        type: str # will be defined by child classes

    @property
    def __geo_interface__(self):
        return self.dict()

# Geometry Collection extends _GeometryBase instead of BaseModel
class GeometryCollection(_GeometryBase):
    """GeometryCollection Model"""

    type: str = Field("GeometryCollection", const=True)
    geometries: List[Geometry]

# another class that only has coordinates
class _GeometryWithCoordinatesBase(_GeometryBase):
    """Base class for geometry models containing coordinates"""

    coordinates: Any  # will be constrained in child classes


class Point(_GeometryWithCoordinatesBase):
    """Point Model"""

    type: str = Field("Point", const=True)
    coordinates: Position

Geometry = Union[Point, MultiPoint, LineString, MultiLineString, Polygon, MultiPolygon, GeometryCollection]
```

another option instead of this Union is to define Geometry (and a new type GeometryWithCoordinates) like:

```python
from typing import Protocol

class GeometryWithCoordinates(Protocol):
    coordinates: Position


class Geometry(Protocol):
    coordinates: Position
    type: str
```

**Comment by vincentsarago** [comment]
fyi I added `__geo_interface__` to `GeometryCollection` in #64 as for the other topic, to be honest I'm not sure I get it totally

**Comment by philvarner** [comment]
You mean you don't get the reason why it's useful for classes to implement __geo_interface__? I can explain if that's the question.

**Comment by vincentsarago** [comment]
> You mean you don't get the reason why it's useful for classes to implement geo_interface? I can explain if that's the question.

no the other issue 

> GeometryCollection is defined as a Geometry in GeoJSON, but there's no relationship between it and either _GeometryBase or the Geometry Union.

**Comment by philvarner** [comment]
If I want to check if an object is a Geometry, I have to write something like:

```
if isinstance(obj, Geometry) or isinstance(obj, GeometryCollection)
```

instead of just `isinstance(obj, Geometry)`, even though GeometryCollection is a type of Geometry (in geojson). 

but if GeometryCollection implement __geo_interface__ now, maybe using that with a Protocol would be better anyway.

**Comment by vincentsarago** [comment]
closing this because I think `__geo_interface__` fixed the original issue.
