### ISSUE TITLE
geojson-pydantic types expect dicts and not json

### ISSUE THREAD

**Issue by p1-dta** [developmentseed/geojson-pydantic#63]
The JSON validator of Pydantic expect a string json-formatted.

I understand why it's a good thing to validate python dict object with a valid geojson structure, but what if I already have a geojson string and I want to validate this string with the geojson-pydantic types?

Sure I can `json.loads()` before but I think it should be automated by the pydantic type.
Also, validate string is coherent with the `pydantic.Json` validator.

**Comment by vincentsarago** [comment]
@Vikka I'm not sure what you are trying to do, could you write down some pseudo code please? 

pydantic comes with https://pydantic-docs.helpmanual.io/usage/models/#helper-functions which is maybe what you are looking for 

```python
from geojson_pydantic import Feature

f = '{"type": "Feature", "geometry": {"type": "Polygon", "coordinates": [[[13.38272, 52.46385], [13.42786, 52.46385], [13.42786, 52.48445], [13.38272, 52.48445], [13.38272, 52.46385]]]}}'

Feature.parse_raw(f)
Feature(type='Feature', geometry=Polygon(coordinates=[[(13.38272, 52.46385), (13.42786, 52.46385), (13.42786, 52.48445), (13.38272, 52.48445), (13.38272, 52.46385)]], type='Polygon'), properties=None, id=None, bbox=None)
```

**Comment by vincentsarago** [comment]
FYI I'm going to move this over the `discussion` because I don't think this is an `issue`
