### ISSUE TITLE
Polygon from_bounds method

### ISSUE THREAD

**Issue by ghost** [developmentseed/geojson-pydantic#75]
The polygon method has the [from_bounds](https://github.com/developmentseed/geojson-pydantic/blob/master/geojson_pydantic/geometries.py#L179) method for building a polygon from boundaries. This is cool functionality! But often in python projects the shapely library is used. There is also a Polygon class with the [from_bounds](https://github.com/shapely/shapely/blob/a0f8a31a18d5384f0a04ee8e8b2d089b37c186cc/shapely/geometry/polygon.py#L316) method. The construction takes place in a similar way, but the polygon is built in the other direction) Is it possible to make the construction of a polygon similar in shapely?

**Comment by vincentsarago** [comment]
👋 @jetwolf the order was specifically changed after https://github.com/developmentseed/geojson-pydantic/issues/48 to make it follow the geojson specification 

> A linear ring MUST follow the right-hand rule with respect to the
area it bounds, i.e., exterior rings are counterclockwise, and
holes are clockwise.

ref: https://datatracker.ietf.org/doc/html/rfc7946#section-3.1.6

this is also mentioned in https://github.com/shapely/shapely/issues/1319


I feel this should be fixed on shapely side tbh

**Comment by jetwolf** [comment]
Thanks for the answer! And thanks for your library!
