### ISSUE TITLE
Problem with "wkt" method.

### ISSUE THREAD

**Issue by impocode** [developmentseed/geojson-pydantic#78]
When inheriting from the Point class, the "wkt" method does not work as I expect. It uses the class name to build wkt. It's right?
Example:

```python
from geojson_pydantic import geometries as geom
class PointType(geom.Point):
    ... (my custom logic)

test = PointType(coordinates=[123, 123])
print(test.wkt)

>>> POINTTYPE (123.0 123.0)
```
I am expecting to get POINT (123.0 123.0) for example to use this in a database.

**Comment by vincentsarago** [comment]
yeah it's because of https://github.com/developmentseed/geojson-pydantic/blob/61048e3618b335a4ef1a8bfa0c132db22c2c022e/geojson_pydantic/geometries.py#L65

I'm not sure if we can easily fix that.

for now I would recommend to do 
```python
from geojson_pydantic import geometries as geom
class Point(geom.Point):
    ... (my custom logic)

test = Point(coordinates=[123, 123])
```

**Comment by vincentsarago** [comment]
> And what is the problem of implementation now? 

the problem right now is that the `wkt` method use `self.__class__.__name__.upper()`, so if your class is name POINTTYPE, it will using `POINTTYPE`.

https://github.com/developmentseed/geojson-pydantic/blob/61048e3618b335a4ef1a8bfa0c132db22c2c022e/geojson_pydantic/geometries.py#L62-L65


> Why can't you implement your own _wkt_type for each geometry class.

you can, by probably do 👇 

```python
class PointType(geom.Point):
    ... (my custom logic)

    @property
    def _wkt_type(self) -> str:
        """Return the WKT name of the geometry."""
        return self.__class__.__name__.upper()
```

**Comment by eseglem** [comment]
What if you changed it to something more like: 

```python
    @property
    def _wkt_type(self) -> str:
        """Return the WKT name of the geometry."""
        return self.type.upper()
```

Since type MUST exist, and can't be modified.
