### ISSUE TITLE
Parsing method for `Geometry`

### ISSUE THREAD

**Issue by hawkaa** [developmentseed/geojson-pydantic#8]
Hi,

Right now I am in situation where I'd like to parse a PostGIS geometry into the Geometry models from this library. However, I don't know upfront which geometry type I'm dealing with.

I just wondered if it could be this library's responsibility of providing a method for parsing a geometry and returning the contents with the correct model. What do you think?

If so, I've been back and forth on where to do this. I think I've settled on putting a new function in `utils.py` or `parser.py` called `parse_geometry_obj` (same naming convention as pydantic `parse_obj`)  The function would return a `Geometry` type which is a union of all geometries.

Alternatively, we turn `_GeometryBase` into `Geometry` and override `parse_obj`, but I come from a functional background so inheritance like that feels odd and inflexible to me. In my world, we would get rid of the base class and add the geo interface to all the classes in the union.

Let me know what you think. I'd love to put up a PR. Should be really simple if we decide how to do it.

**Comment by geospatial-jeff** [comment]
> I think I've settled on putting a new function in `utils.py` or `parser.py` called `parse_geometry_obj`

I think this is the way to go.  This use case is almost identical to shapely's [`geom.shape` method](https://github.com/Toblerity/Shapely/blob/master/shapely/geometry/geo.py#L66-L120) and they have taken a similar approach.

**Comment by drewbo** [comment]
I love the `geom.shape` function and this seems like a solid approach even if it's slightly odd to have as a separate function and not a class method. Let's roll with it for now and see how it goes
